### ISSUE TITLE
Can't start nmap-viewer

### ISSUE THREAD

**Issue by jofab-sys** [psyray/nmap-viewer#2]
Hi, localhost:3001 is not starting.

I'm running a **Ubuntu 20.04 server on WSL2**. I installed manually nodejs and npm. 
I get some errors when doing nmap run build (sudo or not sudo).

Then server -s build -l 3001 & command fails as well.

Can you help me to fix the issue ?
Thanks. Regards.

```
sudo npm run build

> nmap-viewer@0.1.0 build /home/efabenh/nmap-viewer
> react-scripts build
``
/home/efabenh/nmap-viewer/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
   

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/efabenh/nmap-viewer/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nmap-viewer@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nmap-viewer@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-10-02T15_55_37_188Z-debug.log
efabenh@E-5CG22925XX:~/nmap-viewer$ sudo cat /root/.npm/_logs/2024-10-02T15_55_37_188Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle nmap-viewer@0.1.0~prebuild: nmap-viewer@0.1.0
6 info lifecycle nmap-viewer@0.1.0~build: nmap-viewer@0.1.0
7 verbose lifecycle nmap-viewer@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle nmap-viewer@0.1.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/efabenh/nmap-viewer/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle nmap-viewer@0.1.0~build: CWD: /home/efabenh/nmap-viewer
10 silly lifecycle nmap-viewer@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle nmap-viewer@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle nmap-viewer@0.1.0~build: Failed to exec build script
13 verbose stack Error: nmap-viewer@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid nmap-viewer@0.1.0
15 verbose cwd /home/efabenh/nmap-viewer
16 verbose Linux 5.10.102.1-microsoft-standard-WSL2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error nmap-viewer@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the nmap-viewer@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

sudo serve -s build -l 3001 &
[1] 30937
efabenh@E-5CG22925XX:~/nmap-viewer$ /usr/local/lib/node_modules/serve/build/main.js:4
import { cwd as getPwd, exit, env as env2, stdout } from "node:process";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

[1]+  Exit 1                  sudo serve -s build -l 3001

**Comment by psyray** [comment]
Look at my response in https://github.com/psyray/nmap-viewer/issues/1#issuecomment-2389059946
Tool old nodejs, use adsf to install the latest one

**Comment by jofab-sys** [comment]
Hi, thanks for quick reply. It worked with adsf. Maybe you should update install.sh to indicate user to install adsf first.
